stages:
  - validate

lint-sql:
  image: alpine:3.20
  stage: validate
  script:
    - apk add --no-cache bash grep
    - bash scripts/static_check.sh

check-terraform:
  image: hashicorp/terraform:1.8
  stage: validate
  script:
    - terraform -chdir=infra/terraform fmt -check
    - terraform -chdir=infra/terraform init -backend=false
    - terraform -chdir=infra/terraform validate

static-checks:
  image: alpine:3.20
  stage: validate
  script:
    - apk add --no-cache bash grep
    - bash scripts/static_check.sh
